version: "3.3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: lepress
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  mail:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    restart: always
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
